apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cart
spec:
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: flask-cart
        image: amay1794/flask-cart
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-cart-svc
spec:
  type: NodePort 
  selector:
    app: cart
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30005
    
